data:
  image: busybox:latest
  volumes:
    - ./:/code
  entrypoint: tail -f /dev/null

php:
  build: docker/php
  working_dir: /code
  volumes_from:
    - data
  expose:
    - 9000
  links:
    - db
    - mailcatcher

nginx:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./:/code
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
  links:
    - php

mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1080:1080"

db:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: zfg
    MYSQL_USER: root
    MYSQL_PASSWORD: root